// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FR9TaDTuZ6eZ5KQG1ZrlSSoYhjjTZLI',
    appId: '1:951126233515:web:45514cc5a3be00823b42ee',
    messagingSenderId: '951126233515',
    projectId: 'finaldemo-1035b',
    authDomain: 'finaldemo-1035b.firebaseapp.com',
    databaseURL: 'https://finaldemo-1035b-default-rtdb.firebaseio.com',
    storageBucket: 'finaldemo-1035b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXsuYNr3E-7Eq0FiUUPFI35T7mHXTLBY',
    appId: '1:951126233515:android:3560e7415a3a16a13b42ee',
    messagingSenderId: '951126233515',
    projectId: 'finaldemo-1035b',
    databaseURL: 'https://finaldemo-1035b-default-rtdb.firebaseio.com',
    storageBucket: 'finaldemo-1035b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7dVpEgNordNNU_aqtSS5GBsffg946KQ0',
    appId: '1:951126233515:ios:320aa45bc32603aa3b42ee',
    messagingSenderId: '951126233515',
    projectId: 'finaldemo-1035b',
    databaseURL: 'https://finaldemo-1035b-default-rtdb.firebaseio.com',
    storageBucket: 'finaldemo-1035b.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7dVpEgNordNNU_aqtSS5GBsffg946KQ0',
    appId: '1:951126233515:ios:42625d96d032b8fb3b42ee',
    messagingSenderId: '951126233515',
    projectId: 'finaldemo-1035b',
    databaseURL: 'https://finaldemo-1035b-default-rtdb.firebaseio.com',
    storageBucket: 'finaldemo-1035b.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
